version: 2
jobs:
  build:
    working_directory: ~/GoTrack-WebApp
    docker:
      - image: circleci/ruby:2.3.7-jessie-node-browsers
        environment:
          RAILS_ENV: test
          DATABASE_URL: postgresql://root:@127.0.0.1:5432/gotrack-test
      - image: circleci/postgres:9.5-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: gotrack-test
    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - gem-cache
            - gem-cache

      - run: gem install bundler && bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: gem-cache-{{ checksum "Gemfile.lock" }}

      - run: bundle exec rake db:create db:migrate

      - run: bundle exec rake test

      - type: store_test_results
        path: ~/GoTrack-WebApp/coverage
